#!/usr/bin/sh

sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width          0
bspc config window_gap            5

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding 30

# always floating
bspc rule -a feh state=floating center=on
bspc rule -a mpv state=floating center=on
bspc rule -a sxiv state=floating center=on

# 1
bspc rule -a kitty desktop='^1' focus=on follow=on
# 2
bspc rule -a Chromium desktop='^2' focus=on follow=on
bspc rule -a Brave-browser desktop='^2' focus=on follow=on
# 3
bspc rule -a Thunar desktop='^3' focus=on follow=on
bspc rule -a Pcmanfm desktop='^3' focus=on follow=on
bspc rule -a qBittorrent desktop='^3' focus=on follow=on
# 4
bspc rule -a TelegramDesktop desktop='^4' focus=on follow=on
#5
bspc rule -a lxappearance desktop='^5' focus=on follow=on
#6

#autostart
xset r rate 360 60
xsetroot -cursor_name left_ptr
$HOME/.config/polybar/launch.sh
xwallpaper --maximize $HOME/Pictures/Wallpaper/*
picom -b &
redshift -t 6500:1000 &
lxsession &
setxkbmap gb &
numlockx on &
