#! /bin/bash

[colors]
background = #CC282828
foreground = #ebdbb2
red = #CC241D
green = #55ff55
yellow = #ffff55
blue = #5555ff
purple = #ff55ff
cyan = #55ffff
white = #bbbbbb
black = #b5d5ff

[bar/example]
width = 100%
height = 24
;offset-x = 1%
;offset-y = 1%
;radius = 5.0
fixed-center = true
;bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1
line-color = #f00

border-size = 5
border-color = #00000000

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 1

font-0 = "CozetteVector:style=Medium:antialias=true:size=8;2"

modules-left = bspwm
modules-center = date 
modules-right = weather network volume memory cpu

;tray-position = right
;tray-padding = 2
;tray-background = #0063ff

wm-restack = bspwm

override-redirect = true

;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev

cursor-click = pointer
cursor-scroll = ns-resize

separator = |

[module/bat]
type = custom/script
exec = echo $(cat /sys/class/power_supply/BAT1/capacity)%
exec-if = ping wttr.in -c 1
interal = 600
format-prefix = "BAT: "
format-prefix-foreground = #5b

[module/weather]
type = custom/script
exec = curl -s 'wttr.in?format=%C+%t'
exec-if = ping wttr.in -c 1
interal = 600
format-prefix = "WEA: "
format-prefix-foreground = #5b

[module/sound]
type = custom/script
exec = pamixer --get-volume-human
exec-if = pamixer
interal = 0.5
format-prefix = "VOL: "
format-prefix-foreground = #5b


[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#0a81f5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/bspwm]
type = internal/bspwm

label-focused = %name%
label-focused-background = ${colors.red}
label-focused-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.white}
label-empty-padding = 1

; Separator in between workspaces
;label-separator = |

[module/mpd]
type = internal/mpd
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>

icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

label-song-maxlen = 25
label-song-ellipsis = true

[module/xbacklight]
type = internal/xbacklight
output = eDP1
format = <label>
format-prefix = "BL: "
format-prefix-foreground = #5b
label = %percentage%%

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

[module/cpu]
type = internal/cpu
interval = 0.5
format = <label>
label = %percentage%%
format-prefix = "CPU: "
format-prefix-foreground = #5b

[module/memory]
type = internal/memory
interval = 2
label = %percentage_used%%
format-prefix = "RAM: "
format-prefix-foreground = #5b

[module/network]
type = internal/network
interface = enp4s0
interval = 1.0
label-connected = "%downspeed% - %upspeed%"
label-disconnected = "check ur eth!"
label-disconnected-foreground = ${color.red}
format-connected-prefix = "NET: "
format-connected-prefix-foreground = #5b

[module/date]
type = internal/date
interval = 1

date = %a, %d %b at %R
label = %date%

[module/volume]
type = internal/volume
;speaker_mixer = Speaker
;headphone_mixer = Headphone
;headphone_control_numid = 9

;format-volume-background = #933484
;format-volume-underline = #9d6294
;format-volume-overline = #9d6294
;format-volume-padding = 2
format-volume-prefix = "VOL: "
format-volume-prefix-foreground = #5b

;format-muted-background = #933484
;format-muted-underline = #9d6294
;format-muted-overline = #9d6294
;format-muted-padding = 2
format-muted-prefix = "VOL: "
format-muted-prefix-foreground = #5b

label-volume = %percentage%
label-muted = muted

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP1

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <label-charging>

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <label-discharging>

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
;format-full = <label-full>

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = Charging: %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = Discharging: %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
label-full = Fully charged!

[module/temperature]
type = internal/temperature

; Seconds to sleep between updates
; Default: 1
interval = 1

; Thermal zone to use
; To list all the zone types, run 
; $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 0

; Full path of temperature sysfs path
; Use `sensors` to find preferred temperature source, then run
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
; to find path to desired file
; Default reverts to thermal zone setting
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp1_input

; Base temperature for where to start the ramp (in degrees celsius)
; Default: 0
base-temperature = 20

; Threshold temperature to display warning label (in degrees celsius)
; Default: 80
warn-temperature = 60

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 5
margin-bottom = 5
